name: CI

on:
  push:
    branches: [main]
    
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Docker Login
        run: docker login -u ${{ secrets.USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Build and push Docker images
        run: |
          docker build -t andreymoraesfriedel/botlojasfabricia:latest .
          docker push andreymoraesfriedel/botlojasfabricia:latest
